
' Sprite control
CONST MOB_LEFT = $0300 
CONST MOB_TOP = $0100 

' Backtab objects
CONST CHEST = $0803 + 8 * 8

' Controller directions
CONST DISK_N = 1
CONST DISK_NE = 5
CONST DISK_NW = 7
CONST DISK_S = 3
CONST DISK_SE = 6
CONST DISK_SW = 8
CONST DISK_E = 2
CONST DISK_W = 4

' Screen borders
CONST MIN_X = 8
CONST MAX_X = 159
CONST MIN_Y = 16
CONST MAX_Y = 96

' Enemy directions
CONST ENEMY_N = 1
CONST ENEMY_E = 2
CONST ENEMY_S = 3
CONST ENEMY_W = 4

' Shot directions
CONST SHOT_N = 1
CONST SHOT_E = 2
CONST SHOT_S = 3
CONST SHOT_W = 4
CONST SHOT_SPEED=3