' Sprites
CONST SPRITE_PLAYER = $0801 + 0 * 8 
CONST SPRITE_ENEMY = $0802 + 1 * 8

' Sprite control
CONST MOB_LEFT = $0300 
CONST MOB_TOP = $0100 

' Backtab objects
CONST CHEST = $0803 + 2 * 8

' Controller directions
CONST DISK_N = 1
CONST DISK_NE = 5
CONST DISK_NW = 7
CONST DISK_S = 3
CONST DISK_SE = 6
CONST DISK_SW = 8
CONST DISK_E = 2
CONST DISK_W = 4

' Screen borders
CONST MIN_X = 8
CONST MAX_X = 159
CONST MIN_Y = 8
CONST MAX_Y = 96